-- ============================================================================
-- Synonym-Erweiterung v3 — Restliche Lücken schließen
-- ============================================================================
-- Idempotent: ON CONFLICT DO NOTHING
-- Fokus: Produkte die mit dem verbesserten Algorithmus trotzdem nicht matchen
-- ============================================================================

INSERT INTO ingredient_synonyms (canonical, synonym) VALUES
  -- Milchprodukte & Käse (häufig in Angeboten)
  ('Milch', 'frischmilch'),
  ('Milch', 'h-milch'),
  ('Milch', 'vollmilch'),
  ('Milch', 'fettarme milch'),
  ('Milch', 'weidemilch'),
  ('Milch', 'alpenmilch'),
  ('Milch', 'landmilch'),
  ('Joghurt', 'jogurt'),
  ('Joghurt', 'fruchtjoghurt'),
  ('Joghurt', 'naturjoghurt'),
  ('Joghurt', 'trinkjoghurt'),
  ('Joghurt', 'joghurt mild'),
  ('Quark', 'speisequark'),
  ('Quark', 'magerquark'),
  ('Sahne (Schlagsahne)', 'schlagsahne'),
  ('Sahne (Schlagsahne)', 'kochsahne'),
  ('Sahne (Schlagsahne)', 'sprühsahne'),
  ('Sahne (Schlagsahne)', 'kaffeesahne'),
  ('Butter', 'süßrahmbutter'),
  ('Butter', 'sauerrahmbutter'),
  ('Butter', 'markenbutter'),
  ('Butter', 'deutsche markenbutter'),
  ('Butter', 'irische butter'),
  ('Käse (gerieben)', 'reibekäse'),
  ('Käse (gerieben)', 'streukäse'),
  ('Käse (gerieben)', 'pizzakäse'),
  ('Käse (gerieben)', 'gratinkäse'),
  ('Käse (gerieben)', 'emmentaler'),
  ('Käse (gerieben)', 'gouda'),
  ('Käse (gerieben)', 'edamer'),
  ('Käse (gerieben)', 'maasdamer'),
  ('Käse (gerieben)', 'tilsiter'),
  ('Mozzarella', 'burrata'),
  ('Mozzarella', 'büffelmozzarella'),
  ('Feta', 'hirtenkäse'),
  ('Feta', 'schafskäse'),
  ('Feta', 'fetakäse'),
  ('Parmesan', 'parmigiano'),
  ('Parmesan', 'grana padano'),
  ('Frischkäse', 'philadelphia'),
  ('Frischkäse', 'brotaufstrich'),
  ('Mascarpone', 'mascarpone'),
  ('Crème fraîche', 'creme fraiche'),
  ('Crème fraîche', 'schmand'),
  ('Skyr', 'skyr'),

  -- Kefir, Pudding, Cheddar, Camembert (bisher komplett fehlend)
  ('Joghurt', 'kefir'),
  ('Käse (gerieben)', 'cheddar'),
  ('Käse (gerieben)', 'camembert'),
  ('Käse (gerieben)', 'brie'),
  ('Sahne (Schlagsahne)', 'pudding'),

  -- Fleisch (Angebotsformat oft anders als Rezept)
  ('Hähnchenbrust', 'hähnchenbrustfilet'),
  ('Hähnchenbrust', 'hähnchen filet'),
  ('Hähnchenbrust', 'chicken breast'),
  ('Hähnchenbrust', 'hähnchenfilet'),
  ('Hähnchenbrust', 'poulet'),
  ('Hackfleisch (gemischt)', 'hackfleisch'),
  ('Hackfleisch (gemischt)', 'gehacktes'),
  ('Hackfleisch (gemischt)', 'hack'),
  ('Hackfleisch (gemischt)', 'mett'),
  ('Hackfleisch (gemischt)', 'tatar'),
  ('Hackfleisch (gemischt)', 'rinderhack'),
  ('Hackfleisch (gemischt)', 'schweinehack'),
  ('Rindersteak', 'rumpsteak'),
  ('Rindersteak', 'hüftsteak'),
  ('Rindersteak', 'entrecôte'),
  ('Rindersteak', 'ribeye'),
  ('Rindersteak', 'rinderfilet'),
  ('Schweinefilet', 'schweinemedaillons'),
  ('Schweinefilet', 'schweinelende'),
  ('Schinken', 'kochschinken'),
  ('Schinken', 'räucherschinken'),
  ('Schinken', 'schwarzwälder'),
  ('Schinken', 'parmaschinken'),
  ('Schinken', 'serranoschinken'),
  ('Putenbrust', 'putenbrustfilet'),
  ('Putenbrust', 'putenschnitzel'),
  ('Putenbrust', 'putenfilet'),
  ('Putenbrust', 'truthahn'),

  -- Fisch
  ('Lachs (Filet)', 'lachsfilet'),
  ('Lachs (Filet)', 'räucherlachs'),
  ('Lachs (Filet)', 'stremellachs'),
  ('Lachs (Filet)', 'graved lachs'),
  ('Lachs (Filet)', 'wildlachs'),
  ('Thunfisch (Dose)', 'thunfischfilet'),
  ('Garnelen', 'shrimps'),
  ('Garnelen', 'scampi'),
  ('Garnelen', 'riesengarnelen'),
  ('Garnelen', 'eismeergarnelen'),
  ('Garnelen', 'gambas'),

  -- Obst (Angebotsformat)
  ('Apfel', 'äpfel'),
  ('Apfel', 'braeburn'),
  ('Apfel', 'elstar'),
  ('Apfel', 'gala'),
  ('Apfel', 'granny smith'),
  ('Apfel', 'pink lady'),
  ('Apfel', 'jonagold'),
  ('Banane', 'bananen'),
  ('Banane', 'bio-bananen'),
  ('Zitrone', 'zitronen'),
  ('Zitrone', 'bio-zitronen'),
  ('Orange', 'orangen'),
  ('Orange', 'navel'),
  ('Orange', 'blutorangen'),
  ('Erdbeeren', 'erdbeerschale'),
  ('Heidelbeeren', 'blaubeeren'),
  ('Himbeeren', 'himbeerschale'),
  ('Weintrauben', 'trauben'),
  ('Weintrauben', 'tafeltrauben'),

  -- Gemüse
  ('Tomate (frisch)', 'tomaten'),
  ('Tomate (frisch)', 'rispentomaten'),
  ('Tomate (frisch)', 'cherrytomaten'),
  ('Tomate (frisch)', 'strauchtomaten'),
  ('Tomate (frisch)', 'romatomaten'),
  ('Tomate (frisch)', 'cocktailtomaten'),
  ('Paprika', 'paprikaschoten'),
  ('Paprika', 'spitzpaprika'),
  ('Paprika', 'gemüsepaprika'),
  ('Zwiebel', 'zwiebeln'),
  ('Zwiebel', 'speisezwiebeln'),
  ('Zwiebel', 'rote zwiebeln'),
  ('Zwiebel', 'gemüsezwiebeln'),
  ('Kartoffeln', 'speisekartoffeln'),
  ('Kartoffeln', 'festkochend'),
  ('Kartoffeln', 'mehligkochend'),
  ('Kartoffeln', 'drillinge'),
  ('Kartoffeln', 'frühkartoffeln'),
  ('Gurke', 'salatgurke'),
  ('Gurke', 'schlangengurke'),
  ('Gurke', 'minigurken'),
  ('Karotte', 'karotten'),
  ('Karotte', 'möhren'),
  ('Karotte', 'bundmöhren'),
  ('Champignons', 'pilze'),
  ('Champignons', 'steinpilze'),
  ('Champignons', 'pfifferlinge'),
  ('Champignons', 'austernpilze'),
  ('Eisbergsalat', 'kopfsalat'),
  ('Eisbergsalat', 'romana'),
  ('Eisbergsalat', 'salatherzen'),
  ('Eisbergsalat', 'blattsalat'),
  ('Brokkoli', 'broccoli'),
  ('Zucchini', 'zucchini'),

  -- Backwaren
  ('Brot', 'bauernbrot'),
  ('Brot', 'vollkornbrot'),
  ('Brot', 'roggenbrot'),
  ('Brot', 'mischbrot'),
  ('Brot', 'dinkelbrot'),
  ('Brot', 'ciabatta'),
  ('Toastbrot', 'sandwichtoast'),
  ('Toastbrot', 'buttertoast'),
  ('Toastbrot', 'vollkorntoast'),
  ('Brötchen', 'aufbackbrötchen'),
  ('Brötchen', 'sonntagsbrötchen'),
  ('Brötchen', 'laugenbrötchen'),
  ('Brötchen', 'laugenstange'),
  ('Brötchen', 'croissant'),
  ('Brötchen', 'baguette'),

  -- Nudeln & Reis
  ('Spaghetti', 'spaghettini'),
  ('Spaghetti', 'linguine'),
  ('Nudeln', 'penne'),
  ('Nudeln', 'fusilli'),
  ('Nudeln', 'farfalle'),
  ('Nudeln', 'rigatoni'),
  ('Nudeln', 'tagliatelle'),
  ('Nudeln', 'bandnudeln'),
  ('Reis', 'basmatireis'),
  ('Reis', 'jasminreis'),
  ('Reis', 'langkornreis'),
  ('Reis', 'risottoreis'),
  ('Reis', 'milchreis'),

  -- Snacks & Süßes (bisher kaum abgedeckt)
  ('Schokolade', 'vollmilchschokolade'),
  ('Schokolade', 'zartbitterschokolade'),
  ('Schokolade', 'tafelschokolade'),
  ('Kekse', 'butterkekse'),
  ('Kekse', 'doppelkeks'),
  ('Kekse', 'schokokeks'),
  ('Kekse', 'cookies'),
  ('Chips', 'kartoffelchips'),
  ('Chips', 'stapelchips'),

  -- Getränke-Zutaten die in Rezepten vorkommen
  ('Weißwein', 'weisswein'),
  ('Weißwein', 'pinot grigio'),
  ('Weißwein', 'riesling'),
  ('Weißwein', 'chardonnay'),
  ('Rotwein', 'merlot'),
  ('Rotwein', 'cabernet'),

  -- Grundzutaten
  ('Mehl', 'weizenmehl'),
  ('Mehl', 'dinkelmehl'),
  ('Mehl', 'vollkornmehl'),
  ('Zucker', 'rohrzucker'),
  ('Zucker', 'puderzucker'),
  ('Zucker', 'brauner zucker'),
  ('Honig', 'blütenhonig'),
  ('Honig', 'waldhonig'),
  ('Honig', 'akazienhonig'),
  ('Olivenöl', 'natives olivenöl'),
  ('Olivenöl', 'extra vergine'),
  ('Sonnenblumenöl', 'pflanzenöl'),
  ('Sonnenblumenöl', 'bratöl'),
  ('Sonnenblumenöl', 'speiseöl')

ON CONFLICT DO NOTHING;

-- Verify: Anzahl Synonyme nach Insert
SELECT count(*) as total_synonyms FROM ingredient_synonyms;
